// <auto-generated>
// Copied from https://github.com/dotnet/aspnetcore/blob/v6.0.6/src/Mvc/Mvc.TagHelpers/test/TestableHtmlGenerator.cs
// Standard Changes:
//  - Pulling out global usings
//  - Using file scoped namespaces
//  - Changing of the namespace
// File Specific:
//  - Disable warning CS1591 about XML docs
// </auto-generated>

namespace ICG.AspNetCore.Utilities.UnitTesting.TagHelpers.FromFramework;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public class TestModelValidatorProvider : CompositeModelValidatorProvider
{
    // Creates a provider with all the defaults - includes data annotations
    public static CompositeModelValidatorProvider CreateDefaultProvider(IStringLocalizerFactory stringLocalizerFactory = null)
    {
        var options = Options.Create(new MvcDataAnnotationsLocalizationOptions());
        options.Value.DataAnnotationLocalizerProvider = (modelType, localizerFactory) => localizerFactory.Create(modelType);

        var providers = new IModelValidatorProvider[]
        {
            new DefaultModelValidatorProvider(),
            new DataAnnotationsModelValidatorProvider(
                new ValidationAttributeAdapterProvider(),
                options,
                stringLocalizerFactory)
        };

        return new TestModelValidatorProvider(providers);
    }

    public TestModelValidatorProvider(IList<IModelValidatorProvider> providers)
        : base(providers)
    {
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member